spring:
  application:
    name: nupay_serviceAPI

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/EmanateServicesAPI
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8082

nupay:
  base-url: ${NUPAY_BASE_URL:http://localhost:8081}